### ISSUE TITLE
Problemer med join

### ISSUE THREAD

**Issue by ellvtr** [GeoForum/veiledning02#1]
![komm1](https://cloud.githubusercontent.com/assets/12038749/7711360/4c3c7094-fe6a-11e4-946e-d383f06b8105.png)
![komm2](https://cloud.githubusercontent.com/assets/12038749/7711364/51fc60c0-fe6a-11e4-9a21-69094ec9b904.png)

Har lastet ned arbeidsledighet og hjertekar-dødelighet, se /data/ (opprinnelig xls, ligger også i ods og csv format).

Har vasket data og lagt dem inn i lokal postgis-database, se data01.sql.
Har også lagt inn kommuner fra kartverket i postgis - først lagret som shp, siden importert via shp2pgsql og psql - se /data/kommuner.txt.

Tabellene skal joines men har ikke unik nøkkel som fx kommune-nummer, de har kun kommunenavn å joine på.

SQL er ikke min sterkeste side, er litt tvil om hvordan dette gjøres. I /data/data02.sql har jeg prøvd litt forskjellig bla med LIKE. Klarer å joine 416 av 434 rekker med SQL.

I QGIS klarer jeg også å joine 416 av 434 rekker - se screenshot av join.
Andre screenshot viser de kommuner med lilla farge som ikke har data etter join.

``` sql
select 
    a.kommnavn ,
    k.navn
from 
    test01.arbeidsledighet as a, 
    test01.kommuner as k
where 
    --a.kommnavn like k.navn -- 416 rows
    k.navn like a.kommnavn -- 416 rows 
    --k.navn like a.kommnavn || '%' -- 445 rows due to ie Sel and Selje matches
```

**Comment by alexanno** [comment]
Hva med å bruke FTS i PG? 

http://www.postgresql.org/docs/9.4/static/textsearch-intro.html#TEXTSEARCH-MATCHING 

WHERE to_tsvector(k.navn) @@ to_tsquery(a.kommnavn);

Mange kommuner har samiske navn - og noen har samme kommunenavn men forskjellige fylker - da ligger fylkesnavnet inne.

**Comment by ellvtr** [comment]
Fikk det til med qgis med manuell editering. Det tok mye tid å finne en løsning. Fikk ikke prøvd FTS i PG.

**Comment by ellvtr** [comment]
Fikk det til med qgis med manuell editering. Det tok mye tid å finne en løsning  - brukte store deler av søndag, tirsdag og onsdag på dette. Fikk ikke prøvd FTS i PG.

Besrekrevet i join.md, linkes fra README.md.
